In [3]:
import pandas as pd
import numpy as np

### Простейший алгоритм обучения перцептрона 

In [7]:
x = np.array([[1, 1, 0.3], [1, 0.4, 0.5], [1, 0.7, 0.8]])
y = np.array([1, 1, 0])
w = np.array([0., 0., 0.])


def predict(expl, weight):
    return int(expl.dot(weight.T))


for _ in range(20):
    for i in range(x.shape[0]):
        p = predict(x[i], w)
        if p != y[i]:
            w = w + (y[i] - p) * x[i]
        print(w)

[1.  1.  0.3]
[1.  1.  0.3]
[ 0.   0.3 -0.5]
[ 1.   1.3 -0.2]
[ 1.   1.3 -0.2]
[ 0.   0.6 -1. ]
[ 1.   1.6 -0.7]
[ 1.   1.6 -0.7]
[ 0.   0.9 -1.5]
[ 1.   1.9 -1.2]
[ 1.   1.9 -1.2]
[ 0.   1.2 -2. ]
[ 1.   2.2 -1.7]
[ 1.   2.2 -1.7]
[ 0.   1.5 -2.5]
[ 1.   2.5 -2.2]
[ 2.   2.9 -1.7]
[ 0.   1.5 -3.3]
[ 1.   2.5 -3. ]
[ 2.   2.9 -2.5]
[ 0.   1.5 -4.1]
[ 1.   2.5 -3.8]
[ 2.   2.9 -3.3]
[ 1.   2.2 -4.1]
[ 1.   2.2 -4.1]
[ 2.   2.6 -3.6]
[ 2.   2.6 -3.6]
[ 0.   0.6 -4.2]
[ 2.   1.4 -3.2]
[ 2.   1.4 -3.2]
[ 1.   0.4 -3.5]
[ 2.   0.8 -3. ]
[ 2.   0.8 -3. ]
[ 2.   0.8 -3. ]
[ 3.   1.2 -2.5]
[ 2.   0.5 -3.3]
[ 2.   0.5 -3.3]
[ 3.   0.9 -2.8]
[ 2.   0.2 -3.6]
[ 2.   0.2 -3.6]
[ 3.   0.6 -3.1]
[ 3.   0.6 -3.1]
[ 2.  -0.4 -3.4]
[ 3.00000000e+00  3.33066907e-16 -2.90000000e+00]
[ 3.00000000e+00  3.33066907e-16 -2.90000000e+00]
[ 2.  -1.  -3.2]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3.  -0.6 -2.7]
[ 3. 

### NumPy tricks

In [72]:
a = np.array([[1, 2, 32, 2, 5], [3, 4, 2, 6, 2]])
b = np.array([[50, 60]])

d = np.concatenate((a, b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [71]:
d

array([[ 1,  2, 32,  2,  5, 50],
       [ 3,  4,  2,  6,  2, 60]])

#### Умножение векторов

In [32]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0, 1, 0, 2, 0])

a * b

array([0, 2, 0, 8, 0])

In [31]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0, 1, 0, 2, 0])

a * b.T

array([0, 2, 0, 8, 0])

#### Умножение матриц

In [21]:
a = np.array([1, 0, 1, 0])

b = np.array([[1, 2, 0, 1], 
              [3, 4, 0, 1], 
              [5, 6, 1, 0], 
              [7, 8, 3, 2]])

a.dot(b)

array([6, 8, 1, 1])

In [47]:
w = np.array([[1, 2, 3, 4, 5]]).T
x = np.array([[0, 1, 0, 2, 0]]).T
b = 0.5

w.T.dot(x) + b

array([[10.5]])

#### Умножение векторов

In [54]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0, 1, 0, 2, 0])

a.dot(b)

10

In [55]:
a.shape

(5,)

In [49]:
a.dot(b.T)

10

In [52]:
a.T.dot(b.T)

10

#### Транспонирование

In [33]:
b = np.array([[1, 2, 0, 1], 
              [3, 4, 0, 1], 
              [5, 6, 1, 0], 
              [7, 8, 3, 2]])

b.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [0, 0, 1, 3],
       [1, 1, 0, 2]])

In [39]:
a = np.array([[1, 2, 3, 4, 5]])
a.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

### Разные функции

In [ ]:
## Определим разные полезные функции

def sigmoid(x):
    """сигмоидальная функция, работает и с числами, и с векторами (поэлементно)"""
    return 1 / (1 + np.exp(-x))

def sigmoid_prime(x):
    """производная сигмоидальной функции, работает и с числами, и с векторами (поэлементно)"""
    return sigmoid(x) * (1 - sigmoid(x))

### Free

In [18]:
A = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11], [4, 8, 12]])

B = np.array([[1, 5, 9]]).T

C = np.array([[1, 2, 3, 4, 5, 6]])

D = np.array([3, 4, 1]).T

(A.dot(B)).dot(C) == A.dot(B.dot(C))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [19]:
F1 = np.array([[-6, 2, 5], [-4, 1, -5], [-3, -2, 8]])
F2 = np.array([[5, 2, -5], [-8, -10, 4], [9, -7, 1]])
F1.dot(F2)

array([[ -1, -67,  43],
       [-73,  17,  19],
       [ 73, -42,  15]])

In [20]:
F2.dot(F1)

array([[-23,  22, -25],
       [ 76, -34,  42],
       [-29,   9,  88]])